module.exports =
//	"CREATE DATABASE newdatabase20140306;"
	"CREATE DATABASE newdatabase20140219;"
//	+ "\nUSE newdatabase20140219;"
//	+ "\nDROP TABLE IF EXISTS admeshtable;"
	+ "\nCREATE TABLE admeshtable ("
	+ "\n  id int(10) unsigned NOT NULL AUTO_INCREMENT,"
	+ "\n  hash char(16) DEFAULT NOT NULL,"
	+ "\n  minX float DEFAULT NOT NULL,"
	+ "\n  maxX float DEFAULT NOT NULL,"
	+ "\n  minY float DEFAULT NOT NULL,"
	+ "\n  maxY float DEFAULT NOT NULL,"
	+ "\n  minZ float DEFAULT NOT NULL,"
	+ "\n  maxZ float DEFAULT NOT NULL,"
	+ "\n  facetsOverallBefore int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsOverallAfter int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon1Before int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon1After int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon2Before int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon2After int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon3Before int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon3After int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDisconBefore int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDisconAfter int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDegenerate int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsRemoved int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsAdded int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsReversed int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  volume float DEFAULT NOT NULL,"
	+ "\n  parts int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  edgesFixed int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  edgesBackwards int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  normalsFixed int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  PRIMARY KEY (id)"
	+ "\n) CHARSET=utf8;"
