module.exports =
	"CREATE DATABASE newdatabase20140313;"
	+ "\nUSE newdatabase20140313;"
//	+ "\nDROP TABLE IF EXISTS admeshtable;"
	+ "\nCREATE TABLE admeshtable ("
	+ "\n  id int(10) unsigned NOT NULL AUTO_INCREMENT,"
	+ "\n  hash char(16) DEFAULT NOT NULL,"
	+ "\n  volume float DEFAULT NOT NULL,"
	+ "\n  parts int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  minX float DEFAULT NOT NULL,"
	+ "\n  maxX float DEFAULT NOT NULL,"
	+ "\n  minY float DEFAULT NOT NULL,"
	+ "\n  maxY float DEFAULT NOT NULL,"
	+ "\n  minZ float DEFAULT NOT NULL,"
	+ "\n  maxZ float DEFAULT NOT NULL,"
	+ "\n  PRIMARY KEY (id)"
	+ "\n) CHARSET=utf8;"
