module.exports =
	"CREATE DATABASE /*!32312 IF NOT EXISTS newdatabase20140224 /*!40100 DEFAULT CHARACTER SET utf8 */;"
	+ "\nUSE newdatabase20140224;"
	+ "\nDROP TABLE IF EXISTS admeshtable;"
	+ "\nCREATE TABLE admeshtable ("
	+ "\n  id int(10) unsigned NOT NULL AUTO_INCREMENT,"
	+ "\n  hash char(16) DEFAULT NOT NULL,"
	+ "\n  minX float DEFAULT NOT NULL,"
	+ "\n  maxX float DEFAULT NOT NULL,"
	+ "\n  minY float DEFAULT NOT NULL,"
	+ "\n  maxY float DEFAULT NOT NULL,"
	+ "\n  minZ float DEFAULT NOT NULL,"
	+ "\n  maxZ float DEFAULT NOT NULL,"
	+ "\n  facetsOverallBefore int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsOverallAfter int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon1Before int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon1After int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon2Before int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon2After int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon3Before int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDiscon3After int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDisconBefore int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDisconAfter int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsDegenerate int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsRemoved int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsAdded int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  facetsReversed int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  volume float DEFAULT NOT NULL,"
	+ "\n  parts int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  edgesFixed int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  edgesBackwards int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  normalsFixed int(10) unsigned DEFAULT NOT NULL,"
	+ "\n  PRIMARY KEY (id)"
	+ "\n)  ENGINE=InnoDB DEFAULT CHARSET=utf8;"
	+ "\n/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;"
	+ "\n/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;"
	+ "\n/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;"
	+ "\n/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;"
