CREATE TABLE stlUploads (
'id'		integer PRIMARY KEY,
'hash'	integer,
'minX'	integer,
'maxX'	integer,
'minY'	integer,
'maxY'	integer,
'minZ'	integer,
'maxZ'	integer,
'facetsOverallBefore'	integer,
'facetsOverallAfter'	integer,
'facetsDiscon1Before'	integer,
'facetsDiscon1After'	integer,
'facetsDiscon2Before'	integer,
'facetsDiscon2After'	integer,
'facetsDiscon3Before'	integer,
'facetsDiscon3After'	integer,
'facetsDisconBefore'	integer,
'facetsDisconAfter'		integer,
'facetsDegenerate'		integer,
'facetsRemoved'			integer,
'facetsAdded'			integer,
'facetsReversed'		integer,
'volume'			integer,
'parts'				integer,
'edgesFixed'		integer,
'edgesBackwards'	integer,
'normalsFixed'		integer,
);